### ISSUE TITLE
[Optimization] Improve user experience

### ISSUE THREAD

**Issue by erdengk** [apache/shenyu-dashboard#186]
When configuring multiple plugins, you need to switch back and forth between each tab. But the current front-end setting is that as long as you click an option in one tab, other tabs are automatically retracted.

![image](https://user-images.githubusercontent.com/37730787/157396569-8d026cf3-a006-4464-bc98-5614c162af8b.png)

It is recommended to set the tab to not automatically retract unless the user clicks.

**Comment by erdengk** [comment]
The page is re-rendered every time it is clicked, so when a new option is clicked, the tab returns automatically.
To solve this problem, it may be possible to put the expansion information of the tab into the global variable area.
I'm trying to solve this problem, if anyone has other suggestions please @erdengk 
If you want to fix this too, please comment and let me know.
thanks～

**Comment by dengliming** [comment]
Here's where we are now. see https://github.com/apache/shenyu-dashboard/pull/233
