### ISSUE TITLE
[BUG]Front-end components may have bugs

### ISSUE THREAD

**Issue by erdengk** [apache/shenyu-dashboard#208]
It would be better if these display problems could be improved.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/37730787/174841236-e0618b96-d8fe-4d1c-9e47-f70ea9188341.png">

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/37730787/174840758-e6980907-a92b-4ca9-8266-dced9af8ffeb.png">

**Comment by dengliming** [comment]
@daiwenyu Can you help to cc?

**Comment by dengliming** [comment]
@erdengk Could you provide your browser and version?

**Comment by erdengk** [comment]
@dengliming 
yes
<img width="486" alt="image" src="https://user-images.githubusercontent.com/37730787/183290913-b5d97166-f784-4ae8-879b-a4f63d0f8b1c.png">


100.0.4896.88（正式版本） (arm64)

**Comment by tydhot** [comment]
@Leridy check this plz

**Comment by dengliming** [comment]
@Leridy The fastest way is run as docker.

> docker pull apache/shenyu-admin
> docker network create shenyu
> docker run -d -p 9095:9095 --net shenyu apache/shenyu-admin

**Comment by erdengk** [comment]
@Leridy  good job
