### ISSUE TITLE
[Question] Add a new resource.

### ISSUE THREAD

**Issue by Lifeng-Lv** [apache/shenyu-dashboard#224]
is the parent resource necessary? can i create a new top resource?

![image](https://user-images.githubusercontent.com/35800871/183260637-cedbceda-f697-42df-8ce8-7e54144dacca.png)

**Comment by Lifeng-Lv** [comment]
The backend recently modified the code for parameter verification, causing some bugs here. The main problem is that the frontend verification, backend verification and database verification are inconsistent. I tried to fix it all, but I don't know which is correct.

**Comment by dengliming** [comment]
I think the parent menu is not required. so you can fix the backend verification.

**Comment by Lifeng-Lv** [comment]
Database.
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/35800871/183279347-f08f8d8a-df74-4549-9156-49005f229628.png">

Backend.
![image](https://user-images.githubusercontent.com/35800871/183280930-f02efd8f-21d3-442b-847a-6cfeec1e0d55.png)

Frontend.
![image](https://user-images.githubusercontent.com/35800871/183280955-893ecf0c-7d01-4ef0-9468-64f9870d2579.png)


okay, I will fix this bug according to the frontend verification.

**Comment by Lifeng-Lv** [comment]
This is frontend bug, not backend.
