### ISSUE TITLE
The Plugin display is abnormal

### ISSUE THREAD

**Issue by islaiyp** [apache/shenyu-dashboard#268]
if the plugin's config is an empty string, not null, the entire page display is abnormal, show as blank, the console shows a json parsing error.

**Comment by islaiyp** [comment]
the version of shenyu is 2.5.0

**Comment by dengliming** [comment]
Can you try 2.5.1?

**Comment by islaiyp** [comment]
> Can you try 2.5.1?

sry, don't wanna try 2.5.1, but I aleardy solved this problem.
