### ISSUE TITLE
[Task] add a switch button in plugin configuration page 

### ISSUE THREAD

**Issue by salmanthasleem** [apache/shenyu-dashboard#273]
Hello
@tian-pengfei created an issue in the apache/shenyu repo - [https://github.com/apache/shenyu-dashboard/issues/274](https://github.com/apache/shenyu-dashboard/issues/274)
Please correct me if I'm wrong on the following statement,
I investigated the code a little bit and  it seems like adding a switch button in plugin configuration page for greater interactivity can be achieved in apache/shenyu-dashboard
If so I'd like to handle this issue
Thanks

**Comment by tian-pengfei** [comment]
yes , it need to be achieved in apache/shenyu-dashboard

**Comment by tian-pengfei** [comment]
I transfered that issue to this repo ,so I close this issue
