### ISSUE TITLE
[Task] add a switch button in plugin configuration page

### ISSUE THREAD

**Issue by tian-pengfei** [apache/shenyu-dashboard#274]
### Description

Add a switch button in plugin configuration page fot greater interactivity.

![image](https://user-images.githubusercontent.com/42602026/229362523-af7695cb-321a-4cee-a4dc-5e91bac5428d.png)

### Task List

1.elegant interface
2.turn on or off plugin

**Comment by tian-pengfei** [comment]
> Hi I'm currently attepting this, I would want to know if this change is to be done in the shenyu-dashboard?or is it in this repo?


yes , it need to be achieved in apache/shenyu-dashboard

**Comment by salmanthasleem** [comment]
![Screenshot from 2023-04-03 15-57-44](https://user-images.githubusercontent.com/67478065/229484952-89761e9a-707d-438d-b46d-aa6a61633ea2.png)

Hi, Is this what is expected? Can you let me know if I'm on the right track? Now when it's clicked it needs to reverse the horizontal alignment?

**Comment by tian-pengfei** [comment]
> ![Screenshot from 2023-04-03 15-57-44](https://user-images.githubusercontent.com/67478065/229484952-89761e9a-707d-438d-b46d-aa6a61633ea2.png)
> 
> Hi, Is this what is expected? Can you let me know if I'm on the right track? Now when it's clicked it needs to reverse the horizontal alignment?

![image](https://user-images.githubusercontent.com/42602026/229498236-ff2683d9-aec1-48c1-b7f1-079fe9c3f008.png)
this button style look better.

![image](https://user-images.githubusercontent.com/42602026/229500170-7bb437e5-2a75-4655-93d2-c33cb192f26c.png)
 
Maybe you can try add a white bar,then put this button on that. But that doesn't necessarily look good,you need to try . I hope you can find a nice typography.good luck

**Comment by salmanthasleem** [comment]
Want to confirm if the expected output is as the following screenshots?
![Screenshot from 2023-04-03 20-51-49](https://user-images.githubusercontent.com/67478065/229559200-0f6a890f-5c27-402c-88ff-7d38134d9aea.png)
![Screenshot from 2023-04-03 20-52-12](https://user-images.githubusercontent.com/67478065/229559236-20e65560-10eb-456c-9535-f17ff8b8af23.png)

**Comment by salmanthasleem** [comment]
Hi, Im raising a PR with what I've done. I may have missed the actual requirements, if so please point out , I will amend the changes accordingly. Thanks

**Comment by tian-pengfei** [comment]
> 
![image](https://user-images.githubusercontent.com/42602026/230088758-1ec90020-ae9b-445a-8ec6-680c2ca819c9.png)

`Sign` means plugin name , `Authentication `means  plugin category,  that `Close` is plugin state , that shoud  same as button state(picture is wrong).

**Comment by salmanthasleem** [comment]
Thanks , I'll work on it

**Comment by salmanthasleem** [comment]
Hi,I updated my PR, please let me know if I'm missing anything, Thanks
