### ISSUE TITLE
`/config/dict` page Popover exception

### ISSUE THREAD

**Issue by kerwin612** [apache/shenyu-dashboard#370]
![image](https://github.com/apache/shenyu-dashboard/assets/3371163/175d6630-8edf-4541-b234-b80b702dfa51)
![image](https://github.com/apache/shenyu-dashboard/assets/3371163/28727ad9-7701-461c-96d8-fd618415e6d3)

* Title uses incorrect locale key
* Label not uses locale
* The spaces before and after the `:` are not in the same position

**Comment by VampireAchao** [comment]
Make it rain issues! This one's mine!

**Comment by kerwin612** [comment]
> Make it rain issues! This one's mine!

already fixed: #371
