### ISSUE TITLE
Edit Resouce generate resource error

### ISSUE THREAD

**Issue by moremind** [apache/shenyu-dashboard#381]
![image](https://github.com/apache/shenyu-dashboard/assets/20184263/9aeb697e-93fb-4571-a932-5644d15e2112)

**Comment by moremind** [comment]
@VampireAchao @eurecalulu  pls check this?

**Comment by eurecalulu** [comment]
> @VampireAchao @eurecalulu pls check this?

Thanks for reporting,  I'll look into it now.

**Comment by moremind** [comment]
> > @VampireAchao @eurecalulu pls check this?
> 
> Thanks for reporting, I'll look into it now.

no matter, you can check it at another time
