### ISSUE TITLE
Fix UnknownType in frontend

### ISSUE THREAD

**Issue by moremind** [apache/shenyu-dashboard#382]
![image](https://github.com/apache/shenyu-dashboard/assets/20184263/24f2e217-ae03-414c-be3b-6d8c6bbc3042)

the require type is `NO`, but the result is UnknownType

**Comment by eurecalulu** [comment]
<img width="1383" alt="截屏2023-12-21 10 43 04" src="https://github.com/apache/shenyu-dashboard/assets/116816752/c6a229fc-0efa-4cec-a1b7-9f14ccb5aa7d">
This problem may be in the sql script. When adding these data to the plugin_handle table, ext_obj is null.

**Comment by Ritesh92A** [comment]
Please assign this issue to me I wanted to work on this issue.
