### ISSUE TITLE
[Task] Add Batch Enable/Disable for Selectors and Rules

### ISSUE THREAD

**Issue by kerwin612** [apache/shenyu-dashboard#451]
![20240520082617](https://github.com/apache/shenyu-dashboard/assets/3371163/3923439b-0cb4-4c6a-be02-962ab7e5baab)
**Currently supports enabling or disabling individual data entries, now needs to add support for batch operations.**  

---  

**The API is reusable and was initially designed to support batch operations.**  

* Enable or Disable 'Selector'  
> shenyu-dashboard/src/routes/Plugin/Common/index.js
```
//dispatch type
type: "common/enableSelector",
//dispatch body
payload: {
  list,     //id list: ['XXX', 'YYY']
  enabled,  //target status: true/enable, false/disable
},
```
* Enable or Disable 'Rule'
> shenyu-dashboard/src/routes/Plugin/Common/index.js
```
//dispatch type
type: "common/enableRule",
//dispatch body
payload: {
  list,     //id list: ['XXX', 'YYY']
  enabled,  //target status: true/enable, false/disable
},
```

**Comment by VampireAchao** [comment]
assign me
