### ISSUE TITLE
[task]Add namespace to select common components

### ISSUE THREAD

**Issue by xcsnx** [apache/shenyu-dashboard#460]
Shenyu is currently undergoing namespace adaptation and transformation. The front end needs to develop a universal component that can switch namespaces and can be used in multiple interfaces.
Back-end interface: org.apache.shenyu.admin.controller.NamespaceController.
The prototype is as follows:
<img width="793" alt="nmespace" src="https://github.com/user-attachments/assets/ff6ea75b-c409-49b6-b311-d8a9a481a1e3">

**Comment by xcsnx** [comment]
Backend issues:https://github.com/apache/shenyu/pull/5584

**Comment by VampireAchao** [comment]
assign me
